### ISSUE TITLE
Set emojis to bot messages

### ISSUE THREAD

**Issue by lgmagalhaes88** [lgmagalhaes88/HeroBot#26]
Instead of send messages with ":(" or ":)", send emojis like 😥 and 😀. They can be found here: [Emojipedia](https://emojipedia.org/people/)

**Comment by Pedrohf360** [comment]
It's done! I just replace things like ":(" to ":frowning:" . When a user type ":(" it shows a icon because discord app replace it by ":frowning" automatically, but when bot type same thing it don't happen... dont't have idea the reason why.
